/**
 * Curated emoji dataset for the inline picker.
 * Each entry: { n: name, e: emoji, k: search keywords }
 */
export const emojiData = [
  // Smileys & People
  { n: 'smile', e: '\u{1F60A}', k: 'happy grin face' },
  { n: 'laughing', e: '\u{1F602}', k: 'lol tears joy' },
  { n: 'heart_eyes', e: '\u{1F60D}', k: 'love face' },
  { n: 'thinking', e: '\u{1F914}', k: 'hmm consider' },
  { n: 'wink', e: '\u{1F609}', k: 'blink face' },
  { n: 'sunglasses', e: '\u{1F60E}', k: 'cool face' },
  { n: 'nerd', e: '\u{1F913}', k: 'glasses face' },
  { n: 'cry', e: '\u{1F622}', k: 'sad tear face' },
  { n: 'angry', e: '\u{1F620}', k: 'mad face' },
  { n: 'scream', e: '\u{1F631}', k: 'scared shocked face' },
  { n: 'rolling_eyes', e: '\u{1F644}', k: 'whatever face' },
  { n: 'sleeping', e: '\u{1F634}', k: 'zzz face tired' },
  { n: 'shush', e: '\u{1F92B}', k: 'quiet secret' },
  { n: 'exploding_head', e: '\u{1F92F}', k: 'mind blown shocked' },
  { n: 'party', e: '\u{1F973}', k: 'celebrate hat' },
  { n: 'pleading', e: '\u{1F97A}', k: 'puppy eyes please' },
  { n: 'skull', e: '\u{1F480}', k: 'dead death' },
  { n: 'clown', e: '\u{1F921}', k: 'silly face' },
  { n: 'ghost', e: '\u{1F47B}', k: 'spooky' },
  { n: 'alien', e: '\u{1F47D}', k: 'ufo space' },
  { n: 'robot', e: '\u{1F916}', k: 'bot machine ai' },
  { n: 'poop', e: '\u{1F4A9}', k: 'pile' },

  // Gestures
  { n: 'thumbsup', e: '\u{1F44D}', k: 'yes ok approve like +1' },
  { n: 'thumbsdown', e: '\u{1F44E}', k: 'no bad dislike -1' },
  { n: 'clap', e: '\u{1F44F}', k: 'applause bravo' },
  { n: 'wave', e: '\u{1F44B}', k: 'hello hi bye' },
  { n: 'pray', e: '\u{1F64F}', k: 'thanks please folded hands' },
  { n: 'muscle', e: '\u{1F4AA}', k: 'strong flex bicep' },
  { n: 'point_up', e: '\u261D\uFE0F', k: 'finger up' },
  { n: 'point_right', e: '\u{1F449}', k: 'finger right' },
  { n: 'ok_hand', e: '\u{1F44C}', k: 'perfect fine' },
  { n: 'raised_hand', e: '\u270B', k: 'stop high five' },
  { n: 'fist', e: '\u270A', k: 'punch power' },
  { n: 'handshake', e: '\u{1F91D}', k: 'deal agreement' },
  { n: 'writing_hand', e: '\u270D\uFE0F', k: 'write' },
  { n: 'eyes', e: '\u{1F440}', k: 'look see watch' },
  { n: 'brain', e: '\u{1F9E0}', k: 'mind smart think' },

  // Hearts & Symbols
  { n: 'heart', e: '\u2764\uFE0F', k: 'love red' },
  { n: 'fire', e: '\u{1F525}', k: 'hot flame lit' },
  { n: 'sparkles', e: '\u2728', k: 'magic shiny new' },
  { n: 'star', e: '\u2B50', k: 'gold favorite' },
  { n: 'lightning', e: '\u26A1', k: 'zap electricity thunder' },
  { n: '100', e: '\u{1F4AF}', k: 'hundred perfect score' },
  { n: 'boom', e: '\u{1F4A5}', k: 'explosion' },
  { n: 'rainbow', e: '\u{1F308}', k: 'colors' },
  { n: 'sun', e: '\u2600\uFE0F', k: 'sunny bright' },
  { n: 'moon', e: '\u{1F319}', k: 'night crescent' },
  { n: 'cloud', e: '\u2601\uFE0F', k: 'weather' },
  { n: 'snowflake', e: '\u2744\uFE0F', k: 'cold winter' },

  // Objects & Tools
  { n: 'checkmark', e: '\u2705', k: 'done complete yes' },
  { n: 'cross_mark', e: '\u274C', k: 'no wrong delete' },
  { n: 'warning', e: '\u26A0\uFE0F', k: 'caution alert' },
  { n: 'question', e: '\u2753', k: 'what help' },
  { n: 'exclamation', e: '\u2757', k: 'important alert' },
  { n: 'info', e: '\u2139\uFE0F', k: 'information' },
  { n: 'bulb', e: '\u{1F4A1}', k: 'idea light tip' },
  { n: 'memo', e: '\u{1F4DD}', k: 'note write' },
  { n: 'book', e: '\u{1F4D6}', k: 'read open' },
  { n: 'bookmark', e: '\u{1F516}', k: 'save mark' },
  { n: 'link', e: '\u{1F517}', k: 'chain url' },
  { n: 'paperclip', e: '\u{1F4CE}', k: 'attach' },
  { n: 'scissors', e: '\u2702\uFE0F', k: 'cut' },
  { n: 'lock', e: '\u{1F512}', k: 'secure private' },
  { n: 'key', e: '\u{1F511}', k: 'unlock password' },
  { n: 'magnifying_glass', e: '\u{1F50D}', k: 'search find' },
  { n: 'gear', e: '\u2699\uFE0F', k: 'settings config' },
  { n: 'wrench', e: '\u{1F527}', k: 'tool fix' },
  { n: 'hammer', e: '\u{1F528}', k: 'build tool' },
  { n: 'rocket', e: '\u{1F680}', k: 'launch fast ship' },
  { n: 'trophy', e: '\u{1F3C6}', k: 'win award prize' },
  { n: 'medal', e: '\u{1F3C5}', k: 'win gold first' },
  { n: 'crown', e: '\u{1F451}', k: 'king queen royal' },
  { n: 'gem', e: '\u{1F48E}', k: 'diamond jewel' },
  { n: 'money', e: '\u{1F4B0}', k: 'dollar bag rich' },
  { n: 'clock', e: '\u{1F552}', k: 'time' },
  { n: 'calendar', e: '\u{1F4C5}', k: 'date schedule' },
  { n: 'chart', e: '\u{1F4C8}', k: 'graph up trending' },
  { n: 'chart_down', e: '\u{1F4C9}', k: 'graph down declining' },
  { n: 'clipboard', e: '\u{1F4CB}', k: 'list paste' },
  { n: 'inbox', e: '\u{1F4E5}', k: 'mail receive' },
  { n: 'outbox', e: '\u{1F4E4}', k: 'mail send' },
  { n: 'bell', e: '\u{1F514}', k: 'notification alert ring' },
  { n: 'speaker', e: '\u{1F50A}', k: 'sound volume' },
  { n: 'computer', e: '\u{1F4BB}', k: 'laptop pc' },
  { n: 'phone', e: '\u{1F4F1}', k: 'mobile cell' },
  { n: 'camera', e: '\u{1F4F7}', k: 'photo picture' },
  { n: 'video', e: '\u{1F3AC}', k: 'movie film' },

  // Nature & Animals
  { n: 'dog', e: '\u{1F436}', k: 'puppy pet' },
  { n: 'cat', e: '\u{1F431}', k: 'kitten pet' },
  { n: 'bear', e: '\u{1F43B}', k: 'animal' },
  { n: 'unicorn', e: '\u{1F984}', k: 'magic horse' },
  { n: 'butterfly', e: '\u{1F98B}', k: 'insect pretty' },
  { n: 'bee', e: '\u{1F41D}', k: 'honey insect' },
  { n: 'turtle', e: '\u{1F422}', k: 'slow animal' },
  { n: 'tree', e: '\u{1F333}', k: 'nature green' },
  { n: 'flower', e: '\u{1F33A}', k: 'bloom hibiscus' },
  { n: 'rose', e: '\u{1F339}', k: 'flower love' },
  { n: 'leaf', e: '\u{1F343}', k: 'nature wind' },
  { n: 'mushroom', e: '\u{1F344}', k: 'fungus' },

  // Food & Drink
  { n: 'coffee', e: '\u2615', k: 'tea hot drink' },
  { n: 'beer', e: '\u{1F37A}', k: 'drink cheers' },
  { n: 'wine', e: '\u{1F377}', k: 'drink glass' },
  { n: 'pizza', e: '\u{1F355}', k: 'food' },
  { n: 'cake', e: '\u{1F382}', k: 'birthday food' },
  { n: 'cookie', e: '\u{1F36A}', k: 'snack food' },
  { n: 'apple', e: '\u{1F34E}', k: 'fruit red' },
  { n: 'avocado', e: '\u{1F951}', k: 'fruit green' },

  // Flags & Misc
  { n: 'flag', e: '\u{1F3C1}', k: 'finish checkered' },
  { n: 'pin', e: '\u{1F4CC}', k: 'pushpin location' },
  { n: 'globe', e: '\u{1F30D}', k: 'earth world' },
  { n: 'tada', e: '\u{1F389}', k: 'party celebration congratulations' },
  { n: 'balloon', e: '\u{1F388}', k: 'party celebration' },
  { n: 'gift', e: '\u{1F381}', k: 'present birthday' },
  { n: 'ribbon', e: '\u{1F380}', k: 'bow decoration' },
  { n: 'musical_note', e: '\u{1F3B5}', k: 'music song' },
  { n: 'art', e: '\u{1F3A8}', k: 'palette paint' },
  { n: 'dice', e: '\u{1F3B2}', k: 'game random' },
  { n: 'puzzle', e: '\u{1F9E9}', k: 'piece jigsaw' },
  { n: 'infinity', e: '\u267E\uFE0F', k: 'forever loop' },
  { n: 'recycle', e: '\u267B\uFE0F', k: 'reuse green' },
  { n: 'peace', e: '\u262E\uFE0F', k: 'symbol' },

  // Arrows & Symbols
  { n: 'arrow_right', e: '\u27A1\uFE0F', k: 'next forward' },
  { n: 'arrow_left', e: '\u2B05\uFE0F', k: 'back previous' },
  { n: 'arrow_up', e: '\u2B06\uFE0F', k: 'top' },
  { n: 'arrow_down', e: '\u2B07\uFE0F', k: 'bottom' },
  { n: 'plus', e: '\u2795', k: 'add new' },
  { n: 'minus', e: '\u2796', k: 'remove subtract' },
];
